shortName=webhook
version=4.0.0
name=Webhook \u901A\u77E5
author=xiaochun
indexPage=index
desc=\u901a\u8fc7 Webhook \u76ee\u6807\u63a8\u9001\u7cfb\u7edf\u901a\u77e5\uff0c\u5e76\u8bb0\u5f55\u5165\u7ad9 Webhook \u8bf7\u6c42\u3002
paths=/incoming
